parameters:
#    robin_user.example.class: Robin\UserBundle\Example

services:
#    robin_user.example:
#        class: %robin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
