web:
  image: chalasr/symfony-dev
  volumes:
    - /Users/Robin/Sites/perso/production/portfolio:/var/www
  ports:
    - "8000:8000"
  tty: true
  links:
    - db
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: portfolio
        MYSQL_USER: root
        MYSQL_PASSWORD: root
