portfolio_indexpage:
    path:     /hello/{name}
    defaults: { _controller: PortfolioBundle:Default:index }

portfolio_homepage:
    path:     /
    defaults: { _controller: PortfolioBundle:Default:home }

portfolio_homepage_fr:
    path:     /fr
    defaults: { _controller: PortfolioBundle:Default:homeFr }

portfolio_view:
    path:      /project/{id}
    defaults:  { _controller: PortfolioBundle:Project:view }
    requirements:
        id: \d+

portfolio_add:
    path:     /project/add
    defaults: { _controller: PortfolioBundle:Project:add }

portfolio_index:
    path:     /project
    defaults: { _controller: PortfolioBundle:Project:index }
