robin_test:
    resource: "@RobinTestBundle/Resources/config/routing.yml"
    prefix:   /

robin_works:
    resource: "@RobinWorksBundle/Resources/config/routing.yml"
    prefix:   /

robin_user:
    resource: "@RobinUserBundle/Resources/config/routing.yml"
    prefix:   /

portfolio:
    resource: "@PortfolioBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
