parameters:
#    robin_test.example.class: Robin\TestBundle\Example

services:
#    robin_test.example:
#        class: %robin_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
