<?php

namespace Robin\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
<<<<<<< HEAD
 * ProjectRepository
=======
 * ProjectRepository.
>>>>>>> 9652dbc0f473744fff092f7ee6737f947ed4d7cf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
}
