<?php

namespace Robin\PortfolioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
<<<<<<< HEAD
 * ProjectRepository.
=======
 * ProjectRepository
>>>>>>> github
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
}
