<?php

namespace Robin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
<<<<<<< HEAD
 * UserRepository
=======
 * UserRepository.
>>>>>>> 9652dbc0f473744fff092f7ee6737f947ed4d7cf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
