<?php

namespace Robin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
<<<<<<< HEAD
 * UserRepository.
=======
 * UserRepository
>>>>>>> github
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}
